[package]
name = "postgres_range"
version = "0.9.1"
authors = ["Steven Fackler <sfackler@gmail.com>"]
license = "MIT"
description = "Range support for rust-postgres"
repository = "https://github.com/sfackler/rust-postgres-range"
documentation = "https://sfackler.github.io/rust-postgres-range/doc/v0.9.0/postgres_range"

[features]
with-time = ["time", "postgres-shared/with-time"]
with-chrono = ["chrono", "postgres-shared/with-chrono"]

[dependencies]
time = { version = "0.1", optional = true }
postgres-protocol = "0.3"
chrono = { version = "0.4.0", optional = true }
postgres-shared = "0.4.0"

[dev-dependencies]
postgres = { version = "0.15", features = ["with-time"] }
